[package]
name = "material-components"
version = "0.1.0"
edition = "2024"

[dependencies]
yew = { version="0.21", features=["csr"] }
web-sys = { version = "0.3.82", features = ["Window", "Document"] }
